### ISSUE TITLE
[Placeholder]

### ISSUE THREAD

**Issue by bdotdub** [marcsantiago/search_keyword#1]

**Comment by marcsantiago** [comment]
That's a good idea. Here's a question. If I'm limiting concurrency to 20 goroutines. I can read from each file concurrently and either pipe that into one scanner that limits at 20 or create a new scanner one for each file. The second method ofcourse will probably run into socket and ulimit issues if too many files are present in that directory, unless I also limit the number of files to read from. In your opinion following your feature suggestion, what route would you take and why.
